#!/usr/bin/python3
import os, sys
if len(sys.argv) < 2:
    print('Usage: kio [WORD]')
    print('Find translations for WORD in Esperanto and English.')
    exit(-1)
src = sys.argv[1]
src = src.replace('cx', 'ĉ')
src = src.replace('sx', 'ŝ')
src = src.replace('ux', 'ŭ')
src = src.replace('hx', 'ĥ')
src = src.replace('jx', 'ĵ')
src = src.replace('gx', 'ĝ')
file = open('/usr/share/eodict')
directhit = []
matches = []
for line in file:
    line = line.strip()
    if line.split(' ')[0] == src:
        directhit.append(line)
    elif src in line.split('  ')[-1].strip().split(', '):
        directhit.append(line)
    elif src in line:
        matches.append(line)
if len(directhit) > 0:
    for i in directhit:
        print(i)
else:
    for i in matches:
        print(i)
